---

- name: restart_unifi
  service:
    name: unifi
    state: restarted
    enabled: yes
  become: yes


- name: stop_mongod
  service:
    name: mongodb
    state: stopped
    enabled: no
  become: yes
